add_executable(
		test_tetris_mino
		tetris/mino.cpp
)
target_link_libraries(
		test_tetris_mino
		PRIVATE
		tetris_ui
)

add_executable(
		test_tetris_random
		tetris/random.cpp
)
target_link_libraries(
		test_tetris_random
		PRIVATE
		tetris_ui
)

add_executable(
		test_tetris_actions
		tetris/actions.cpp
)
target_link_libraries(
		test_tetris_actions
		PRIVATE
		tetris_ui
)

add_executable(
		test_model_player_value
		model/player_value.cpp
)
target_link_libraries(
		test_model_player_value
		PRIVATE
		tetris_ai
)
