add_executable(
		test_tetris_mino
		tetris/mino.cpp
)
target_link_libraries(
		test_tetris_mino
		PRIVATE
		tetris_ui
)

add_executable(
		test_tetris_random
		tetris/random.cpp
)
target_link_libraries(
		test_tetris_random
		PRIVATE
		tetris_ui
)

add_executable(
		test_tetris_actions
		tetris/actions.cpp
)
target_link_libraries(
		test_tetris_actions
		PRIVATE
		tetris_ui
)

add_executable(
		test_model_value_speed
		model/value_speed.cpp
)
target_link_libraries(
		test_model_value_speed
		PRIVATE
		tetris_ai
)

add_executable(
		test_buffer
		buffer/buffer.cpp
)
target_link_libraries(
		test_buffer
		PRIVATE
		tetris_ai
)

add_executable(
		test_model_value_batch_speed
		model/value_batch_speed.cpp
)
target_link_libraries(
		test_model_value_batch_speed
		PRIVATE
		tetris_ai
)

add_executable(
		test_rollout
		mcts/rollout.cpp
)
target_link_libraries(
		test_rollout
		PRIVATE
		tetris_ai
)
