model:
  path: "value_1.pt"
  optimizer: "empty"
  cuda: false

mcts:
  C: 5.0
  simu: 200
  batch: 128

buffer:
  path: "buffer/1"
  sample: 10000
  window: 100000

train:
  game: 100
  output: "output"
