model:
  path: "value_1.pt"
  optimizer: "empty"
  cuda: false

mcts:
  C: 5.0
  simu: 200
  batch: 128

buffer:
  path: "buffer/1"
  window: 200000

train:
  game: 300
  num: 32
  batch: 512
  output: "output"
